export function DeterministicTruthBanner() {
  return (
    <section className="mx-6 mt-6 rounded-2xl border border-sky-200 bg-sky-50 p-5 shadow-sm">
      <p className="text-xs font-semibold uppercase tracking-[0.25em] text-sky-700">
        Numerical Source of Truth
      </p>
      <p className="mt-2 text-sm leading-6 text-slate-700">
        Numerical kinematic values in MechSynthCAD are generated by deterministic solver endpoints.
        AI/agent layers assist with validation, planning, interpretation, synthesis direction, and reporting,
        but do not create final engineering values.
      </p>
    </section>
  );
}
