import type { V2AgentMessage, V2MechanismState, V2ProviderStatus } from "@/components/v2/types";

export type V2AcademicReportMode = "Proposal" | "Chapter Draft" | "Result Appendix" | "Supervisor Demo";
export type V2AcademicReportMetadata = { projectTitle: string; studentName: string; department: string; institution: string; level: string; supervisor: string; sessionSemester: string; date: string; mechanismType: string; reportMode: V2AcademicReportMode };
export type V2ReportEvidenceItem = { id: string; label: string; ready: boolean; explanation: string; actionLabel?: string; actionCommand?: string };
export type V2AcademicReportSection = { heading: string; content: string; rows?: Array<[string, string]>; note?: string };
export type V2AcademicReport = { title: string; sections: V2AcademicReportSection[]; markdown: string; evidenceChecklist: V2ReportEvidenceItem[] };

export const sourceOfTruthNote = "Numerical mechanism values in this report are generated by deterministic solver routines. AI/model output is advisory and used only for planning, interpretation, and report drafting.";
export const missingEvidenceText = "Evidence not yet generated. Run deterministic analysis/simulation to populate this section.";

export function defaultAcademicReportMetadata(date = new Date()): V2AcademicReportMetadata {
  return { projectTitle: "Development of an AI-Assisted CAD-Based System for Kinematic Analysis and Synthesis of Planar Mechanisms", studentName: "IBIDUN QUYUM Babatunde", department: "Mechanical Engineering", institution: "Federal University of Technology, Minna", level: "500L", supervisor: "", sessionSemester: "", date: date.toISOString().slice(0, 10), mechanismType: "four_bar", reportMode: "Supervisor Demo" };
}

export function buildAcademicReport(input: { state: V2MechanismState; messages?: V2AgentMessage[]; metadata: V2AcademicReportMetadata; providers?: V2ProviderStatus[] }): V2AcademicReport {
  const { state, messages = [], providers = [] } = input;
  const metadata = { ...input.metadata, mechanismType: state.selectedMechanism };
  const isFour = state.selectedMechanism === "four_bar";
  const sweepForm = isFour ? state.sweepForm : state.sliderCrankSweepForm;
  const sweep = state.sweepResultForReport;
  const result = state.solverResult;
  const synthesis = state.latestSynthesisRecommendations;
  const hasCad = Boolean(result);
  const validationMentioned = messages.some((m) => /validat/i.test(m.text));
  const metadataComplete = Boolean(metadata.projectTitle && metadata.studentName && metadata.department && metadata.institution && metadata.level && metadata.date);
  const checklist: V2ReportEvidenceItem[] = [
    { id: "mechanism", label: "Mechanism selected", ready: Boolean(state.selectedMechanism), explanation: isFour ? "Four-bar linkage selected." : "Slider-crank mechanism selected.", actionLabel: "Open parameters", actionCommand: "Open parameter intake" },
    { id: "parameters", label: "Parameters ready", ready: noMissing(state.inputParameters), explanation: noMissing(state.inputParameters) ? "All mechanism parameter fields contain numeric values." : "One or more numeric parameters need review.", actionLabel: "Open parameters", actionCommand: "Open parameter intake" },
    { id: "analysis", label: "Deterministic analysis result available", ready: Boolean(result), explanation: result ? "Solver result is available for numerical report sections." : missingEvidenceText, actionLabel: "Run analysis", actionCommand: "Run analysis" },
    { id: "sweep", label: "Sweep simulation available", ready: Boolean(sweep), explanation: sweep ? "Sweep sample summary is available." : missingEvidenceText, actionLabel: "Run simulation", actionCommand: "Run simulation" },
    { id: "cad", label: "CAD artifact available", ready: hasCad, explanation: hasCad ? "Current V2 canvas can be used as visualization evidence." : "CAD/SVG canvas needs deterministic result evidence for final capture.", actionLabel: "Open canvas", actionCommand: "Open canvas" },
    { id: "synthesis", label: "Synthesis recommendation available", ready: Boolean(synthesis), explanation: synthesis ? "Recommendation artifact is available." : "Generate recommendation after deterministic analysis.", actionLabel: "Generate recommendation", actionCommand: "Recommend improvement" },
    { id: "validation", label: "Validation matrix available", ready: validationMentioned, explanation: validationMentioned ? "Validation workflow has been opened or discussed." : "Open validation to document workflow checks.", actionLabel: "Open validation", actionCommand: "Validate workflow" },
    { id: "metadata", label: "Report metadata complete", ready: metadataComplete, explanation: metadataComplete ? "Required title-page metadata is populated." : "Complete title-page fields before submission.", actionLabel: "Edit metadata" },
    { id: "model", label: "Model/advisory note included", ready: true, explanation: providers.some((p) => p.status === "configured") ? "Configured model providers are documented as advisory only." : "Local deterministic mode documented; model output remains advisory." },
    { id: "truth", label: "Source-of-truth note included", ready: true, explanation: sourceOfTruthNote },
  ];
  const sections: V2AcademicReportSection[] = [
    { heading: "Title Page metadata block", content: "Supervisor-facing project metadata for academic review.", rows: Object.entries({ "Project title": metadata.projectTitle, "Student name": metadata.studentName, Department: metadata.department, Institution: metadata.institution, Level: metadata.level, Supervisor: metadata.supervisor || "Not yet specified", "Session/Semester": metadata.sessionSemester || "Not yet specified", Date: metadata.date, "Mechanism type": labelMechanism(state.selectedMechanism), "Report mode": metadata.reportMode }) },
    { heading: "Abstract / Summary", content: result ? `This report summarizes deterministic ${labelMechanism(state.selectedMechanism)} analysis evidence and AI-assisted reporting workflow outputs for supervisor review.` : missingEvidenceText },
    { heading: "Aim and Objectives", content: "Aim: develop and demonstrate an AI-assisted CAD-based workflow for kinematic analysis and synthesis of planar mechanisms.", rows: [["Objective 1", "Capture mechanism parameters in a structured engineering workspace."], ["Objective 2", "Use deterministic solver routines as numerical source of truth."], ["Objective 3", "Present analysis, sweep, visualization, recommendation, and validation evidence for review."]] },
    { heading: "Methodology", content: "Parameters are entered in V2, deterministic solver routines generate numerical analysis/sweep outputs, and AI/model features support planning, interpretation, and report drafting only." },
    { heading: "System Architecture", content: "The V2 workspace separates parameter intake, deterministic solver tools, CAD/SVG visualization artifacts, synthesis recommendations, validation, and report export." },
    { heading: "Mechanism Under Study", content: `${labelMechanism(state.selectedMechanism)} is selected for this report.` },
    { heading: "Input Parameters", content: "Current numeric inputs captured from V2 state.", rows: parameterRows(state, sweepForm) },
    { heading: "Deterministic Kinematic Analysis Result", content: result ? "Solver result summary from deterministic routines." : missingEvidenceText, rows: result ? resultRows(result, isFour) : undefined },
    { heading: "Sweep Simulation Result", content: sweep ? "Sweep simulation summary from deterministic sample generation." : missingEvidenceText, rows: sweep ? sweepRows(sweep, sweepForm, isFour ? state.selectedSampleIndex : state.selectedSliderCrankSampleIndex) : undefined },
    { heading: "CAD / SVG Visualization Evidence", content: hasCad ? "CAD/SVG visualization is available in the V2 canvas artifact for capture/export into the final submission." : "CAD/SVG visualization is available in the V2 canvas artifact and should be captured/exported for final submission." },
    { heading: "AI-Assisted Workflow Explanation", content: sourceOfTruthNote },
    { heading: "Design Synthesis / Recommendation", content: synthesis ? summarizeObject(synthesis) : missingEvidenceText },
    { heading: "Validation and Limitations", content: "Independent engineering review is required before physical implementation. Missing checklist items should be completed before supervisor submission." },
    { heading: "Conclusion", content: result ? "The current evidence package is ready for academic review subject to completion of any unresolved checklist items." : missingEvidenceText },
    { heading: "References / Tools Used", content: "MechSynthCAD V2 deterministic solver routines; V2 CAD/SVG artifact view; V2 report builder; optional AI/model advisory workflow." },
    { heading: "Appendix: Raw Solver Output", content: result ? fenced(result) : missingEvidenceText },
  ];
  return { title: metadata.projectTitle, sections, evidenceChecklist: checklist, markdown: toMarkdown(metadata, sections, checklist) };
}
function noMissing(params: Record<string, unknown>) { return Object.values(params).every((v) => typeof v === "number" && !Number.isNaN(v)); }
function labelMechanism(m: string) { return m === "four_bar" ? "Four-Bar Linkage" : "Slider-Crank"; }
function parameterRows(state: V2MechanismState, sweepForm: Record<string, unknown>) { return [...Object.entries(state.inputParameters), ["sweep range", Object.values(sweepForm).join(" → ")]].map(([k, v]) => [String(k), String(v)] as [string, string]); }
function resultRows(result: Record<string, unknown>, isFour: boolean) { const keys = isFour ? ["valid", "mechanism", "mobility", "classification", "grashof_status", "theta2_deg", "theta3_deg", "theta4_deg", "notes"] : ["valid", "mechanism", "slider_position", "transmission_angle_deg", "velocity_analysis", "acceleration_analysis", "notes"]; return keys.filter((k) => result[k] !== undefined).map((k) => [k, typeof result[k] === "object" ? JSON.stringify(result[k]) : String(result[k])] as [string, string]); }
function sweepRows(sweep: Record<string, unknown>, sweepForm: Record<string, unknown>, index: number) { return [["sample_count", sweep.sample_count], ["valid_sample_count", sweep.valid_sample_count], ["invalid_sample_count", sweep.invalid_sample_count], ["sweep start/end/step", Object.values(sweepForm).join(" / ")], ["selected sample index", index]].map(([k, v]) => [String(k), String(v)] as [string, string]); }
function summarizeObject(value: unknown) { return typeof value === "string" ? value : JSON.stringify(value, null, 2); }
function fenced(value: unknown) { return "```json\n" + JSON.stringify(value, null, 2) + "\n```"; }
function toMarkdown(metadata: V2AcademicReportMetadata, sections: V2AcademicReportSection[], checklist: V2ReportEvidenceItem[]) { return [`# ${metadata.projectTitle}`, `**Student:** ${metadata.studentName}`, `**Department:** ${metadata.department}`, `**Institution:** ${metadata.institution}`, `**Level:** ${metadata.level}`, `**Supervisor:** ${metadata.supervisor || "Not yet specified"}`, `**Session/Semester:** ${metadata.sessionSemester || "Not yet specified"}`, `**Date:** ${metadata.date}`, `**Report mode:** ${metadata.reportMode}`, "", `> ${sourceOfTruthNote}`, "", "## Evidence Checklist", ...checklist.map((i) => `- ${i.ready ? "Ready" : "Missing"}: ${i.label} — ${i.explanation}`), "", ...sections.flatMap((s) => [`## ${s.heading}`, s.content, ...(s.rows ? ["", "| Item | Value |", "| --- | --- |", ...s.rows.map(([k, v]) => `| ${k} | ${String(v).replace(/\|/g, "\\|")} |`)] : []), ""])] .join("\n"); }
